SUPABASE_URL="https://dgziyxibuhuyghlyashm.supabase.co"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRneml5eGlidWh1eWdobHlhc2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMzkwMTgsImV4cCI6MjA3NTkxNTAxOH0.sRM3L5HHIIww9jC7f92Ty_BbWjGqtuXL_YnBDChCbfw"

DATABASE_URL="postgresql://postgres:FbjDs4muXE8xhb0N@db.dgziyxibuhuyghlyashm.supabase.co:5432/postgres"